version: '3.1'

services:

  mongo:
    container_name: mongo-onprem
    image: mongo
    restart: always
    # ports:
    #   - 27017:27017
    # volumes:
    #   - mongodata:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password123

  api:
    container_name: api-onprem
    image: api:1
    restart: always
    ports:
      - 3000:80
    environment:
      PORT: 80
      MONGO: 'mongodb://root:password123@mongo:27017'

# volumes:
#   mongodata:
