version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    ports:
      - 3100:27017
    volumes:
      - ./db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: cper2g3-onprem
      MONGO_INITDB_ROOT_PASSWORD: password123

  api:
    image: api:1
    restart: always
    ports:
      - 3000:80
    environment:
      PORT: 80
      MONGO: 'mongodb://cper2g3-onprem:password123@mongo:27017'
